root: ./

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:  
    developers/developers-and-contributors/update-document: contributing/contributing.md
    user-guide/user-guide-query/pinot-query-language: users/user-guide-query/querying-pinot.md
    basics/components/controller#controller-periodic-tasks: configuration-reference/controller.md
    basics/components/controller: basics/components/cluster/controller.md
    basics/components/broker: basics/components/cluster/broker.md
    basics/components/server: basics/components/cluster/server.md
    basics/components/minion: basics/components/cluster/minion.md
    basics/components/tenant: basics/components/cluster/tenant.md
    basics/components/segment: basics/components/table/segment.md
    basics/components/deep-store: basics/components/table/segment/deep-store.md
    basics/components/schema: basics/components/table/schema.md
    basics/concepts: basics/concepts/readme.md
    developers/advanced/troubleshoot-multi-stage-query-engine: reference/troubleshooting/troubleshoot-multi-stage-query-engine.md
    functions-1: users/user-guide-query/function-index.md
    functions/math-functions: functions/math/
    functions/string-functions: functions/string/
    functions/datetime-functions: functions/datetime/
    functions/geospatial-functions: functions/geospatial/
    functions/binary-functions: functions/binary/
    functions/statistical-functions: functions/statistical/
    functions/ip-address-functions: functions/ip-address/
    functions/trigonometric-functions: functions/trigonometric/
    functions/type-conversion-functions: functions/type-conversion/
    functions/null-handling-functions: functions/null-handling/
    functions/vector-functions: functions/vector/
    users/user-guide-query/json-queries: functions/json/
    configuration-reference/functions/distinctcountcpcsketch: functions/sketch/distinctcountcpcsketch.md
    configuration-reference/functions/distinctcounthllplus: functions/sketch/distinctcounthllplus.md
    configuration-reference/functions/distinctcounthllplusmv: functions/sketch/distinctcounthllplusmv.md
    configuration-reference/functions/distinctcountrawcpcsketch: functions/sketch/distinctcountrawcpcsketch.md
    configuration-reference/functions/distinctcountrawhllplus: functions/sketch/distinctcountrawhllplus.md
    configuration-reference/functions/distinctcountrawhllplusmv: functions/sketch/distinctcountrawhllplusmv.md
    configuration-reference/functions/distinctcountrawintegersumtuplesketch: functions/sketch/distinctcountrawintegersumtuplesketch.md
    configuration-reference/functions/distinctcountrawull: functions/sketch/distinctcountrawull.md
    configuration-reference/functions/distinctcounttuplesketch: functions/sketch/distinctcounttuplesketch.md
    configuration-reference/functions/distinctcountull: functions/sketch/distinctcountull.md
    configuration-reference/functions/avgvalueintegersumtuplesketch: functions/sketch/avgvalueintegersumtuplesketch.md
    configuration-reference/functions/sumvaluesintegersumtuplesketch: functions/sketch/sumvaluesintegersumtuplesketch.md
    configuration-reference/functions/clpdecode: functions/clp/clpdecode.md
    configuration-reference/functions/jsonextractindex: functions/json/jsonextractindex.md
    configuration-reference/functions/jsonpathexists: functions/json/jsonpathexists.md
    users/user-guide-query/query-syntax: users/user-guide-query/query-syntax-overview.md
    users/user-guide-query/query-syntax/array-functions: functions/array/
    users/user-guide-query/query-syntax/funnel-analysis: functions/funnel/
    users/user-guide-query/query-syntax/hash-functions: functions/hash/
    users/user-guide-query/query-syntax/url-functions: functions/url/
    users/user-guide-query/query-syntax/windows-functions: functions/window/
    users/user-guide-query/query-syntax/explain-plan-multi-stage: users/user-guide-query/explain-plan-multi-stage.md
    users/user-guide-query/query-syntax/filtering-with-idset: users/user-guide-query/filtering-with-idset.md
    users/user-guide-query/query-syntax/joins: users/user-guide-query/joins.md
    users/user-guide-query/query-syntax/lookup-udf-join: users/user-guide-query/lookup-udf-join.md
    users/user-guide-query/query-syntax/row-expression-comparison: users/user-guide-query/row-expression-comparison.md
    users/user-guide-query/scalar-functions: functions/udf/
    