{
 "title": "Pinot",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Controller Leader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (pinot_controller_LeaderPartitionCount_Value)"
    }
   ]
  },
  {
   "title": "Realtime Table Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_namespace) (pinot_controller_realtimeTableCount_Value)"
    }
   ]
  },
  {
   "title": "Broker Query Rate Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_broker_queries_Count[10m]))"
    }
   ]
  },
  {
   "title": "Broker Query Doc Scan Rate Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_broker_documentsScanned_Count[10m]))"
    }
   ]
  },
  {
   "title": "Broker Query Latency Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_50thPercentile)"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_99thPercentile)"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_999thPercentile)"
    }
   ]
  },
  {
   "title": "Server Total Documents Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (pinot_server_documentCount_Value)"
    }
   ]
  },
  {
   "title": "Server Realtime Consuming Rate Per Table",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_server_realtimeRowsConsumed_Count[5m]))"
    }
   ]
  },
  {
   "title": "Server Table Consuming Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_99thPercentile)"
    }
   ]
  },
  {
   "title": "Table Off-Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (table)(pinot_server_realtime_offheapMemoryUsed_Value) "
    }
   ]
  },
  {
   "title": "Server Memory Map Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name)(pinot_server_memory_mmapBufferUsage_Value) "
    }
   ]
  },
  {
   "title": "Server DirectBuffer Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name)(pinot_server_memory_directBufferUsage_Value) "
    }
   ]
  },
  {
   "title": "Server Query Doc Scanned Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_server_numDocsScanned_Count[10m]))"
    }
   ]
  },
  {
   "title": "Server Query Segment Processed Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_server_numSegmentsProcessed_Count[10m]))"
    }
   ]
  },
  {
   "title": "Server Total Segment Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (pinot_server_segmentCount_Value)"
    }
   ]
  },
  {
   "title": "Server Query Latency Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_50thPercentile)"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_99thPercentile)"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_999thPercentile)"
    }
   ]
  }
 ]
}